### ISSUE TITLE
I was trying to convert the file format, but I got this error and I don't know what the reason is. But even if there is a bug, the converted image will still work, will this make any difference? Will it have an impact on image quality?

### ISSUE THREAD

**Issue by xxd-1223** [icometrix/dicom2nifti#130]
Removing duplicate slice from series
Traceback (most recent call last):
  File "/home/anaconda3/envs/pytorch/lib/python3.8/site-packages/dicom2nifti/convert_dir.py", line 85, in convert_directory
    convert_dicom.dicom_array_to_nifti(dicom_input, nifti_file, reorient)
  File "/home/anaconda3/envs/pytorch/lib/python3.8/site-packages/dicom2nifti/convert_dicom.py", line 117, in dicom_array_to_nifti
    results = convert_generic.dicom_to_nifti(dicom_list, output_file)
  File "/home/anaconda3/envs/pytorch/lib/python3.8/site-packages/dicom2nifti/convert_generic.py", line 103, in dicom_to_nifti
    if common.is_multiframe_dicom(dicom_input):
  File "/home/anaconda3/envs/pytorch/lib/python3.8/site-packages/dicom2nifti/common.py", line 148, in is_multiframe_dicom
    header = dicom_input[0]
IndexError: list index out of range
Removing duplicate slice from series
Traceback (most recent call last):
  File "/home/anaconda3/envs/pytorch/lib/python3.8/site-packages/dicom2nifti/convert_dir.py", line 85, in convert_directory
    convert_dicom.dicom_array_to_nifti(dicom_input, nifti_file, reorient)
  File "/home/anaconda3/envs/pytorch/lib/python3.8/site-packages/dicom2nifti/convert_dicom.py", line 117, in dicom_array_to_nifti
    results = convert_generic.dicom_to_nifti(dicom_list, output_file)
  File "/home/anaconda3/envs/pytorch/lib/python3.8/site-packages/dicom2nifti/convert_generic.py", line 103, in dicom_to_nifti
    if common.is_multiframe_dicom(dicom_input):
  File "/home/anaconda3/envs/pytorch/lib/python3.8/site-packages/dicom2nifti/common.py", line 148, in is_multiframe_dicom
    header = dicom_input[0]
IndexError: list index out of range

**Comment by abrys** [comment]
When running convert_dir directly of converting a directory from command line it will first split the full directory into different series based on the dicom headers. It will then try to convert each series individually, if one of the series fails it will print the actual error but continue to the next series in the directory. So it can be that it converts part of the directory and fails for the rest
