### ISSUE TITLE
OverflowError: Python integer -1024 out of bounds for uint16

### ISSUE THREAD

**Issue by clead6** [icometrix/dicom2nifti#150]
Hi, I am getting this overflow error when converting my image from DICOM to NIFTI. I had quick look through your code, I think one of your conditions for converting to float must be missing when doing the scaling. Let me know if you can fix this.

---------------------------------------------------------------------------
OverflowError                             Traceback (most recent call last)
Cell In[2], [line 4](vscode-notebook-cell:?execution_count=2&line=4)
      [2](vscode-notebook-cell:?execution_count=2&line=2) dicom_path = Path("data/practical1/CT-PET-VI-02/CT_for_PET/")
      [3](vscode-notebook-cell:?execution_count=2&line=3) output_path = Path("data/practical1/ct_for_pet.nii.gz")
----> [4](vscode-notebook-cell:?execution_count=2&line=4) dicom2nifti.dicom_series_to_nifti(dicom_path, output_path, reorient_nifti=False)

File c:\Users\clead\anaconda3\envs\dicom2nifti\Lib\site-packages\dicom2nifti\convert_dicom.py:79, in dicom_series_to_nifti(original_dicom_directory, output_file, reorient_nifti)
     [75](file:///C:/Users/clead/anaconda3/envs/dicom2nifti/Lib/site-packages/dicom2nifti/convert_dicom.py:75)     shutil.copytree(original_dicom_directory, dicom_directory)
     [77](file:///C:/Users/clead/anaconda3/envs/dicom2nifti/Lib/site-packages/dicom2nifti/convert_dicom.py:77)     dicom_input = common.read_dicom_directory(dicom_directory)
---> [79](file:///C:/Users/clead/anaconda3/envs/dicom2nifti/Lib/site-packages/dicom2nifti/convert_dicom.py:79)     return dicom_array_to_nifti(dicom_input, output_file, reorient_nifti)
     [81](file:///C:/Users/clead/anaconda3/envs/dicom2nifti/Lib/site-packages/dicom2nifti/convert_dicom.py:81) except AttributeError as exception:
     [82](file:///C:/Users/clead/anaconda3/envs/dicom2nifti/Lib/site-packages/dicom2nifti/convert_dicom.py:82)     raise exception

File c:\Users\clead\anaconda3\envs\dicom2nifti\Lib\site-packages\dicom2nifti\convert_dicom.py:119, in dicom_array_to_nifti(dicom_list, output_file, reorient_nifti)
    [116](file:///C:/Users/clead/anaconda3/envs/dicom2nifti/Lib/site-packages/dicom2nifti/convert_dicom.py:116) vendor = _get_vendor(dicom_list)
    [118](file:///C:/Users/clead/anaconda3/envs/dicom2nifti/Lib/site-packages/dicom2nifti/convert_dicom.py:118) if vendor == Vendor.GENERIC:
--> [119](file:///C:/Users/clead/anaconda3/envs/dicom2nifti/Lib/site-packages/dicom2nifti/convert_dicom.py:119)     results = convert_generic.dicom_to_nifti(dicom_list, output_file)
    [120](file:///C:/Users/clead/anaconda3/envs/dicom2nifti/Lib/site-packages/dicom2nifti/convert_dicom.py:120) elif vendor == Vendor.SIEMENS:
    [121](file:///C:/Users/clead/anaconda3/envs/dicom2nifti/Lib/site-packages/dicom2nifti/convert_dicom.py:121)     results = convert_siemens.dicom_to_nifti(dicom_list, output_file)

File c:\Users\clead\anaconda3\envs\dicom2nifti\Lib\site-packages\dicom2nifti\convert_generic.py:274, in dicom_to_nifti(dicom_input, output_file)
    [270](file:///C:/Users/clead/anaconda3/envs/dicom2nifti/Lib/site-packages/dicom2nifti/convert_generic.py:270)     nii_image, max_slice_increment = _convert_slice_incement_inconsistencies(dicom_input)
    [271](file:///C:/Users/clead/anaconda3/envs/dicom2nifti/Lib/site-packages/dicom2nifti/convert_generic.py:271) # do the normal conversion
    [272](file:///C:/Users/clead/anaconda3/envs/dicom2nifti/Lib/site-packages/dicom2nifti/convert_generic.py:272) else:
    [273](file:///C:/Users/clead/anaconda3/envs/dicom2nifti/Lib/site-packages/dicom2nifti/convert_generic.py:273)     # Get data; originally z,y,x, transposed to x,y,z
--> [274](file:///C:/Users/clead/anaconda3/envs/dicom2nifti/Lib/site-packages/dicom2nifti/convert_generic.py:274)     data = common.get_volume_pixeldata(dicom_input)
    [276](file:///C:/Users/clead/anaconda3/envs/dicom2nifti/Lib/site-packages/dicom2nifti/convert_generic.py:276)     affine, max_slice_increment = common.create_affine(dicom_input)
    [278](file:///C:/Users/clead/anaconda3/envs/dicom2nifti/Lib/site-packages/dicom2nifti/convert_generic.py:278)     # Convert to nifti

File c:\Users\clead\anaconda3\envs\dicom2nifti\Lib\site-packages\dicom2nifti\common.py:313, in get_volume_pixeldata(sorted_slices)
    [310](file:///C:/Users/clead/anaconda3/envs/dicom2nifti/Lib/site-packages/dicom2nifti/common.py:310) for i, slice_ in enumerate(sorted_slices):
    [311](file:///C:/Users/clead/anaconda3/envs/dicom2nifti/Lib/site-packages/dicom2nifti/common.py:311)     # create copy so we don't load all pixel data on the original slice that is kept in memory
    [312](file:///C:/Users/clead/anaconda3/envs/dicom2nifti/Lib/site-packages/dicom2nifti/common.py:312)     slice_copy = copy.deepcopy(slice_)
--> [313](file:///C:/Users/clead/anaconda3/envs/dicom2nifti/Lib/site-packages/dicom2nifti/common.py:313)     slice_data = _get_slice_pixeldata(slice_copy)
    [314](file:///C:/Users/clead/anaconda3/envs/dicom2nifti/Lib/site-packages/dicom2nifti/common.py:314)     del slice_copy
    [315](file:///C:/Users/clead/anaconda3/envs/dicom2nifti/Lib/site-packages/dicom2nifti/common.py:315)     if combined_dtype is None:

File c:\Users\clead\anaconda3\envs\dicom2nifti\Lib\site-packages\dicom2nifti\common.py:355, in _get_slice_pixeldata(dicom_slice)
    [353](file:///C:/Users/clead/anaconda3/envs/dicom2nifti/Lib/site-packages/dicom2nifti/common.py:353)     data[data > max_value] = numpy.bitwise_or(data[data > max_value], invert_value)
    [354](file:///C:/Users/clead/anaconda3/envs/dicom2nifti/Lib/site-packages/dicom2nifti/common.py:354)     pass
--> [355](file:///C:/Users/clead/anaconda3/envs/dicom2nifti/Lib/site-packages/dicom2nifti/common.py:355) return apply_scaling(data, dicom_slice)

File c:\Users\clead\anaconda3\envs\dicom2nifti\Lib\site-packages\dicom2nifti\common.py:509, in apply_scaling(data, dicom_headers)
    [500](file:///C:/Users/clead/anaconda3/envs/dicom2nifti/Lib/site-packages/dicom2nifti/common.py:500)         rescale_intercept = dicom_headers.RescaleIntercept
    [501](file:///C:/Users/clead/anaconda3/envs/dicom2nifti/Lib/site-packages/dicom2nifti/common.py:501)     # try:
    [502](file:///C:/Users/clead/anaconda3/envs/dicom2nifti/Lib/site-packages/dicom2nifti/common.py:502)     #     # this section can sometimes fail due to unknown private fields
    [503](file:///C:/Users/clead/anaconda3/envs/dicom2nifti/Lib/site-packages/dicom2nifti/common.py:503)     #     if private_scale_slope_tag in dicom_headers:
   (...)
    [507](file:///C:/Users/clead/anaconda3/envs/dicom2nifti/Lib/site-packages/dicom2nifti/common.py:507)     # except:
    [508](file:///C:/Users/clead/anaconda3/envs/dicom2nifti/Lib/site-packages/dicom2nifti/common.py:508)     #     pass
--> [509](file:///C:/Users/clead/anaconda3/envs/dicom2nifti/Lib/site-packages/dicom2nifti/common.py:509)     return do_scaling(data, rescale_slope, rescale_intercept)
    [510](file:///C:/Users/clead/anaconda3/envs/dicom2nifti/Lib/site-packages/dicom2nifti/common.py:510) else:
    [511](file:///C:/Users/clead/anaconda3/envs/dicom2nifti/Lib/site-packages/dicom2nifti/common.py:511)     return data

File c:\Users\clead\anaconda3\envs\dicom2nifti\Lib\site-packages\dicom2nifti\common.py:540, in do_scaling(data, rescale_slope, rescale_intercept, private_scale_slope, private_scale_intercept)
    [537](file:///C:/Users/clead/anaconda3/envs/dicom2nifti/Lib/site-packages/dicom2nifti/common.py:537) else:
    [538](file:///C:/Users/clead/anaconda3/envs/dicom2nifti/Lib/site-packages/dicom2nifti/common.py:538)     # Determine required range
    [539](file:///C:/Users/clead/anaconda3/envs/dicom2nifti/Lib/site-packages/dicom2nifti/common.py:539)     minimum_required, maximum_required = data.min(), data.max()
--> [540](file:///C:/Users/clead/anaconda3/envs/dicom2nifti/Lib/site-packages/dicom2nifti/common.py:540)     minimum_required = min([minimum_required, minimum_required * rescale_slope + rescale_intercept,
    [541](file:///C:/Users/clead/anaconda3/envs/dicom2nifti/Lib/site-packages/dicom2nifti/common.py:541)                             maximum_required * rescale_slope + rescale_intercept])
    [542](file:///C:/Users/clead/anaconda3/envs/dicom2nifti/Lib/site-packages/dicom2nifti/common.py:542)     maximum_required = max([maximum_required, minimum_required * rescale_slope + rescale_intercept,
    [543](file:///C:/Users/clead/anaconda3/envs/dicom2nifti/Lib/site-packages/dicom2nifti/common.py:543)                             maximum_required * rescale_slope + rescale_intercept])
    [545](file:///C:/Users/clead/anaconda3/envs/dicom2nifti/Lib/site-packages/dicom2nifti/common.py:545)     # Determine required datatype from that

OverflowError: Python integer -1024 out of bounds for uint16

**Comment by woctezuma** [comment]
I have a similar issue.

```
$ dicom2nifti DICOM/00009001 output2-00009001/
Traceback (most recent call last):
  File "C:\Users\Wok\AppData\Local\Programs\Python\Python313\Lib\site-packages\dicom2nifti\convert_dir.py", line 86, in convert_directory
    convert_dicom.dicom_array_to_nifti(dicom_input, nifti_file, reorient)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Wok\AppData\Local\Programs\Python\Python313\Lib\site-packages\dicom2nifti\convert_dicom.py", line 121, in dicom_array_to_nifti
    results = convert_siemens.dicom_to_nifti(dicom_list, output_file)
  File "C:\Users\Wok\AppData\Local\Programs\Python\Python313\Lib\site-packages\dicom2nifti\convert_siemens.py", line 79, in dicom_to_nifti
    return convert_generic.dicom_to_nifti(dicom_input, output_file)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Wok\AppData\Local\Programs\Python\Python313\Lib\site-packages\dicom2nifti\convert_generic.py", line 274, in dicom_to_nifti
    data = common.get_volume_pixeldata(dicom_input)
  File "C:\Users\Wok\AppData\Local\Programs\Python\Python313\Lib\site-packages\dicom2nifti\common.py", line 313, in get_volume_pixeldata
    slice_data = _get_slice_pixeldata(slice_copy)
  File "C:\Users\Wok\AppData\Local\Programs\Python\Python313\Lib\site-packages\dicom2nifti\common.py", line 355, in _get_slice_pixeldata
    return apply_scaling(data, dicom_slice)
  File "C:\Users\Wok\AppData\Local\Programs\Python\Python313\Lib\site-packages\dicom2nifti\common.py", line 509, in apply_scaling
    return do_scaling(data, rescale_slope, rescale_intercept)
  File "C:\Users\Wok\AppData\Local\Programs\Python\Python313\Lib\site-packages\dicom2nifti\common.py", line 540, in do_scaling
    minimum_required = min([minimum_required, minimum_required * rescale_slope + rescale_intercept,
                                              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~
OverflowError: Python integer -4096 out of bounds for uint16
```

**Comment by woctezuma** [comment]
For info, I have not encountered any issue with a competitor called [`dcm2niix`](https://github.com/rordenlab/dcm2niix).

```
$ dcm2niix.exe -o output-00009001 DICOM\00009001

Compression will be faster with pigz.exe in the same folder as the executable
Chris Rorden's dcm2niiX version v1.0.20241211  (JP2:OpenJPEG) (JP-LS:CharLS) MSC1942  (64-bit Windows)
Found 56 DICOM file(s)
Warning: Siemens XA exported as classic not enhanced DICOM (issue 236)
Convert 56 DICOM as output-00009001\00009001_T2_SWI_3D_AX_2.5mm_20250206082546_9001_ph (528x576x56x1)
Conversion required 0.609000 seconds.
```
