### ISSUE TITLE
GE Conversion Issues

### ISSUE THREAD

**Issue by cancan101** [icometrix/dicom2nifti#25]
```
Traceback (most recent call last):
  File "/usr/src/app/research/projects/brain/scripts/dicom_to_nifti.py", line 201, in convert_directory
    convert_dicom.dicom_array_to_nifti(dicom_input, nifti_file, reorient)  # noqa: E501
  File "/usr/local/lib/python3.5/dist-packages/dicom2nifti/convert_dicom.py", line 135, in dicom_array_to_nifti
    results = convert_ge.dicom_to_nifti(dicom_list, output_file)
  File "/usr/local/lib/python3.5/dist-packages/dicom2nifti/convert_ge.py", line 74, in dicom_to_nifti
    return _4d_to_nifti(grouped_dicoms, output_file)
  File "/usr/local/lib/python3.5/dist-packages/dicom2nifti/convert_ge.py", line 123, in _4d_to_nifti
    full_block = _get_full_block(grouped_dicoms)
  File "/usr/local/lib/python3.5/dist-packages/dicom2nifti/convert_ge.py", line 171, in _get_full_block
    full_block[:, :, :, index] = data_blocks[index]
ValueError: could not broadcast input array from shape (256,256,3) into shape (256,256,2)
```

**Comment by abrys** [comment]
Can you provide a little more information about the type of data being converted.
This type of error usually occurs if you are converting a 4D dataset (fMRI, DTI, ...) and there are slices missing from one of the timepoints.

The error handling here could be improved significantly however.

**Comment by abrys** [comment]
Added better error handling in this case. Will be included in the next release

**Comment by abrys** [comment]
_get_grouped_dicoms breaking up DICOM volumes #31
