### ISSUE TITLE
Package not usable with pydicom 1.0+

### ISSUE THREAD

**Issue by fedorov** [icometrix/dicom2nifti#3]
Installed with pip install.

```
$ dicom2nifti --help
Traceback (most recent call last):
  File "/Users/fedorov/.pyenv/versions/2.7.8/bin/dicom2nifti", line 14, in <module>
    import dicom2nifti.convert_dir as convert_directory
  File "/Users/fedorov/.pyenv/versions/2.7.8/lib/python2.7/site-packages/dicom2nifti/__init__.py", line 20, in <module>
    from .convert_dicom import dicom_series_to_nifti
  File "/Users/fedorov/.pyenv/versions/2.7.8/lib/python2.7/site-packages/dicom2nifti/convert_dicom.py", line 8, in <module>
    import dicom2nifti.patch_pydicom_encodings
  File "/Users/fedorov/.pyenv/versions/2.7.8/lib/python2.7/site-packages/dicom2nifti/patch_pydicom_encodings.py", line 5, in <module>
    import dicom.charset
ImportError: No module named dicom.charset
```

**Comment by fedorov** [comment]
Workaround: I installed pydicom from source, and `import dicom` doesn't work, I need to import it as `import pydicom`. 

You might want to consider this guide for porting to pydicom 1.0: https://github.com/pydicom/pydicom/wiki/Porting-to-pydicom-1.0

**Comment by abrys** [comment]
We currently do not see porting to pydicom 1.0 as a valid option as unfortunately it is not available (yet) on pypi and thus cannot be installed easily. However I will take a look at making it compatible for those who need pydicom 1.0 for other reasons.

**Comment by abrys** [comment]
We just made a new release https://pypi.python.org/pypi/dicom2nifti/1.2.7.
From now on we should be 1.0.0 compatible.
