### ISSUE TITLE
Unable to handle images touched by dcm4che or Agfa

### ISSUE THREAD

**Issue by neurolabusc** [icometrix/dicom2nifti#85]
dcm4che and [Agfa](https://github.com/rordenlab/dcm2niix/issues/435) (which uses dcm4che) will rename manufacturer private groups. This obfuscation is legal with samples [provided here](https://github.com/neurolabusc/dcm_qa_agfa). This can disrupt dicom2nifti. For example, consider data from a [Philips scanner](https://github.com/rordenlab/dcm2niix/issues/437) - the raw data is converted correctly by dicom2nifti, but if it is touched by dcm4che it will fail (as 2005, 140f has been remapped). A robust solution would be to check the private tag [owner](https://github.com/pydicom/pydicom/blob/master/pydicom/_private_dict.py).

```
dicom2nifti /Users/chris/Neuro/issue437/bad /Users/chris/Neuro/issue437/
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/dicom2nifti/convert_dir.py", line 87, in convert_directory
    convert_dicom.dicom_array_to_nifti(dicom_input, nifti_file, reorient)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/dicom2nifti/convert_dicom.py", line 124, in dicom_array_to_nifti
    results = convert_philips.dicom_to_nifti(dicom_list, output_file)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/dicom2nifti/convert_philips.py", line 56, in dicom_to_nifti
    return _multiframe_to_nifti(dicom_input, output_file)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/dicom2nifti/convert_philips.py", line 239, in _multiframe_to_nifti
    affine = _create_affine_multiframe(multiframe_dicom)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/dicom2nifti/convert_philips.py", line 413, in _create_affine_multiframe
    delta_r = float(first_frame[0x2005, 0x140f][0].PixelSpacing[0])
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pydicom/dataset.py", line 852, in __getitem__
    data_elem = self._dict[tag]
KeyError: (2005, 140f)


```

**Comment by abrys** [comment]
Thanks for supplying the datasets. We will look into this issue.
