### ISSUE TITLE
Single dicom image

### ISSUE THREAD

**Issue by saro92** [icometrix/dicom2nifti#94]
Hey there

I am new to the topic and try to convert a single dicom file (.dcm) to a nifi file. Sadly by running the command (dicom2nifti.convert_directory(path_to_the_file,output_path) the nifti file is not created but there is no error message. Can anyone may help with the issue cause I do not know what I am doing wrong.

thanks a lot

**Comment by blakedewey** [comment]
There is a setting that prevents this. You can change this by running:

```
import dicom2nifti.settings as settings
settings.disable_validate_slicecount()
```

before running `convert_directory`.

**Comment by fiooonna** [comment]
I have the same issue but 

> There is a setting that prevents this. You can change this by running:
> 
> ```
> import dicom2nifti.settings as settings
> settings.disable_validate_slicecount()
> ```
> 
> before running `convert_directory`.

I have the same issue but this does not fix it.

**Comment by robertorojasp06** [comment]
Hi everyone!

I think this is still an open issue.

I run the `dicom2nifti` utility with the `-S` flag but I got this error:
> Traceback (most recent call last):
  File "/home/cosmo/anaconda3/envs/dicom2nifti/lib/python3.10/site-packages/dicom2nifti/convert_dir.py", line 85, in convert_directory
    convert_dicom.dicom_array_to_nifti(dicom_input, nifti_file, reorient)
  File "/home/cosmo/anaconda3/envs/dicom2nifti/lib/python3.10/site-packages/dicom2nifti/convert_dicom.py", line 117, in dicom_array_to_nifti
    results = convert_generic.dicom_to_nifti(dicom_list, output_file)
  File "/home/cosmo/anaconda3/envs/dicom2nifti/lib/python3.10/site-packages/dicom2nifti/convert_generic.py", line 221, in dicom_to_nifti
    if common.is_multiframe_dicom(dicom_input):
  File "/home/cosmo/anaconda3/envs/dicom2nifti/lib/python3.10/site-packages/dicom2nifti/common.py", line 148, in is_multiframe_dicom
    header = dicom_input[0]
IndexError: list index out of range

I used a fresh conda environment with `python=3.10` and `dicom2nifti=2.4.9`.

Also tried with the programatic approach, running the `disable_validate_slicecount()` method from the `settings.py` module, but I got the same error.
